services:
  app_srv:
    hostname: ystuty-service-schedule
    build:
      context: .
      target: build
      dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
      # 8080 is the default port
      - ${EXTERNAL_PORT:-25604}:${SERVER_PORT:-8080}
      # - ${EXTERNAL_MS_PORT:-7484}:${SERVER_MS_PORT:-3000}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - ystuty-network
      - ystuty-service-network
    volumes:
      - ./.env:/home/node/app/.env
    healthcheck:
      test: curl --fail http://localhost:${SERVER_PORT:-8080}${HEALTH_PATH:-/uptime} || exit 1
      interval: 2m
      retries: 3
      start_period: 40s
      timeout: 10s
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  ystuty-network:
    external: true
  ystuty-service-network:
    external: true
