export const OAUTH2_STRATEGY_METADATA = '__OAUTH2_STRATEGY_METADATA__';
export const OAUTH2_REQUIRED_SCOPES = 'OAUTH2_REQUIRED_SCOPES';

export const OAUTH2_MODULE_OPTIONS = 'OAUTH2_MODULE_OPTIONS';
export const OAUTH2_USER_LOADER = 'OAUTH2_USER_LOADER';
export const OAUTH2_USER_VALIDATOR = 'OAUTH2_USER_VALIDATOR';
